### ISSUE TITLE
Лого

### ISSUE THREAD

**Issue by fedKotikeD** [Bluespace-community/Bluespace-Station#112]
### Описание

Сделать лого и иконку сервера в `/Textures/Logo/`

### Параметры

1. Сделать иконку BS14 (сокр.от Bluespace Station 14) в `/Textures/Logo/icon-ru`
2. Сделать баннер Bluespace station 14 в `/Textures/Logo/logo-ru.png`

**Comment by dopoi16-txt** [comment]
Попробую сделать

**Comment by Verslebas** [comment]
закрой issue

**Comment by fedKotikeD** [comment]
А, точно
