### ISSUE TITLE
Добавить бригмедика.

### ISSUE THREAD

**Issue by PuroSlavKing** [Bluespace-community/Bluespace-Station#135]
### Описание

Добавьте, всё в билде есть.

**Comment by fedKotikeD** [comment]
Где он в билде?

**Comment by PuroSlavKing** [comment]
> Где он в билде?

![image](https://github.com/Bluespace-community/Bluespace-Station/assets/103608145/500a4d2b-4b02-4420-97dc-aae45060324d)

**Comment by fedKotikeD** [comment]
> > Где он в билде?
> 
> ![image](https://private-user-images.githubusercontent.com/103608145/295254445-500a4d2b-4b02-4420-97dc-aae45060324d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MTQ1OTgsIm5iZiI6MTcwNDgxNDI5OCwicGF0aCI6Ii8xMDM2MDgxNDUvMjk1MjU0NDQ1LTUwMGE0ZDJiLTRiMDItNDQyMC05N2RjLWFhZTQ1MDYwMzI0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxNTMxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWEwNjgzMGUyMjAwMDhhMDYyOTFhYjIzMzBlMDAxNWE1YjUzY2FiMjQ0MTEwNzFjMTI2MGU5YjgyNWU0N2RiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2T3t0eCUIx6CECqdqZGlboNm9m0aDjo5RYsWsFAUQgg)

Я его как роль не вижу

**Comment by PuroSlavKing** [comment]
> > > Где он в билде?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/103608145/295254445-500a4d2b-4b02-4420-97dc-aae45060324d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MTQ1OTgsIm5iZiI6MTcwNDgxNDI5OCwicGF0aCI6Ii8xMDM2MDgxNDUvMjk1MjU0NDQ1LTUwMGE0ZDJiLTRiMDItNDQyMC05N2RjLWFhZTQ1MDYwMzI0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxNTMxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWEwNjgzMGUyMjAwMDhhMDYyOTFhYjIzMzBlMDAxNWE1YjUzY2FiMjQ0MTEwNzFjMTI2MGU5YjgyNWU0N2RiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2T3t0eCUIx6CECqdqZGlboNm9m0aDjo5RYsWsFAUQgg)
> 
> Я его как роль не вижу

по этому и написано **ДОБАВИТЬ**

**Comment by fedKotikeD** [comment]
> > > > Где он в билде?
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/103608145/295254445-500a4d2b-4b02-4420-97dc-aae45060324d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MTQ1OTgsIm5iZiI6MTcwNDgxNDI5OCwicGF0aCI6Ii8xMDM2MDgxNDUvMjk1MjU0NDQ1LTUwMGE0ZDJiLTRiMDItNDQyMC05N2RjLWFhZTQ1MDYwMzI0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxNTMxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWEwNjgzMGUyMjAwMDhhMDYyOTFhYjIzMzBlMDAxNWE1YjUzY2FiMjQ0MTEwNzFjMTI2MGU5YjgyNWU0N2RiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2T3t0eCUIx6CECqdqZGlboNm9m0aDjo5RYsWsFAUQgg)
> > 
> > 
> > Я его как роль не вижу
> 
> по этому и написано **ДОБАВИТЬ**

Ааа.. ну надо поискать все его вещички. @Indi-vindi11 не хочешь этим заняться?

**Comment by fedKotikeD** [comment]
Попробую внести

**Comment by fedKotikeD** [comment]
К сожалению, по решению https://canary.discord.com/channels/1082913477481476147/1082925447718912040/1242158931690655754 закрывается
